PUPUT_PROGRAMMING_LANGUAGE_CHOICES = (
    ('bash', 'Bash/Shell'),
    ('c', 'C'),
    ('cpp', 'C++'),
    ('csharp', 'C#'),
    ('css', 'CSS'),
    ('diff', 'Diff'),
    ('erlang', 'Erlang'),
    ('html', 'HTML'),
    ('java', 'Java'),
    ('javascript', 'JavaScript'),
    ('json', 'JSON'),
    ('perl', 'Perl'),
    ('php', 'PHP'),
    ('python', 'Python'),
    ('ruby', 'Ruby'),
    ('scala', 'Scala'),
    ('scss', 'SCSS'),
    ('sql', 'SQL'),
    ('vbnet', 'Visual Basic'),
    ('xml', 'XML'),
    ('yaml', 'YAML'),
)
