# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_auto_20150919_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Custom code name')),
                ('content', models.TextField(blank=True, max_length=2000, verbose_name='code')),
                ('active', models.BooleanField(default=False, verbose_name='Activate')),
            ],
            options={
                'verbose_name': 'Custom code',
            },
        ),
    ]
