# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-02 18:32
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager
import wagtail.contrib.table_block.blocks
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailembeds.blocks
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0002_auto_20150919_0925'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blogpage',
            managers=[
                ('extra', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='entrypage',
            name='stream_body',
            field=wagtail.wagtailcore.fields.StreamField((('paragraph', wagtail.wagtailcore.blocks.RichTextBlock()), ('heading', wagtail.wagtailcore.blocks.TextBlock()), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.TextBlock(required=False))))), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('embed', wagtail.wagtailembeds.blocks.EmbedBlock()), ('code', wagtail.wagtailcore.blocks.StructBlock((('language', wagtail.wagtailcore.blocks.ChoiceBlock(choices=[('bash', 'Bash/Shell'), ('c', 'C'), ('cpp', 'C++'), ('csharp', 'C#'), ('css', 'CSS'), ('diff', 'Diff'), ('erlang', 'Erlang'), ('html', 'HTML'), ('java', 'Java'), ('javascript', 'JavaScript'), ('json', 'JSON'), ('perl', 'Perl'), ('php', 'PHP'), ('python', 'Python'), ('ruby', 'Ruby'), ('scala', 'Scala'), ('scss', 'SCSS'), ('sql', 'SQL'), ('vbnet', 'Visual Basic'), ('xml', 'XML'), ('yaml', 'YAML')])), ('code', wagtail.wagtailcore.blocks.TextBlock())), label='Code Snippet'))), blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='body',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, verbose_name='body'),
        ),
    ]
